---
num_clients: 100 # total number of clients
num_local_epochs: 10 # number of local epochs
num_rep_epochs: 5
batch_size: 10
num_rounds: 100
clients_per_round: 10
learning_rate: 0.01
algorithm: fedrep
model_name: cnncifar100

client_resources:
  num_cpus: 2
  num_gpus: 0.5

server_device: cuda:0

dataset:
  name: cifar100
  split: sample
  num_classes: 20
  seed: 42
  num_clients: ${num_clients}
  fraction: 0.83

model:
  _target_: null

fit_config:
  drop_client: false
  epochs: ${num_local_epochs}
  batch_size: ${batch_size}

strategy:
  _target_: fedrep.server.DefaultStrategyPipeline
  algorithm: ${algorithm}
  fraction_fit: 0.0000001 # let this arg useless and `min_fit_clients` decide the final num
  fraction_evaluate: 1.0
  min_fit_clients: ${clients_per_round}
  min_evaluate_clients: 2
  min_available_clients: 2
  evaluate_fn: null
  on_fit_config_fn: null
  on_evaluate_config_fn: null
